# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kmGOMAE4lQ-wNmIetdkwowVZoKW7zzwa
"""

import matplotlib.pyplot as plt
import time
plt.style.use('seaborn-v0_8-whitegrid')
a=input("purpose of the graph")

x=input("x axis values for showing bar in graph")
x=[int(i) for i in x.split()]
x_a=input("what do you want call this x axis")

y=input("y axis values for showing bar in graph (note: same count as x axis)")
y=[int(i) for i in y.split()]
y_a=input("what do you want call this x axis")

#x=[1,2,3]
#y=[2,4,6]

if len(x) != len(y):
  print("x and y length must be same length size")
else:
  fig, ax =plt.subplots(figsize=(8,5))
  columns= ax.bar(x, y, color='#1f77b4', width=0.4, edgecolor='black', linewidth=0.7)
  ax.bar_label(columns, padding=3, fmt='$%gM', fontsize=10, weight='bold')
  ax.set_xlabel(x_a)
  ax.set_ylabel(y_a)
  ax.set_title(a)
  ax.set_ylim(0, max(y) * 1.15)

  '''
  plt.plot(x,y , color ='red')
  plt.fill_between(x,y, color="blue",alpha =0.35)
  plt.bar(x,y,color='green',alpha=0.4)

  plt.xlabel('X Axis')
  plt.ylabel('Y Axis')
  plt.title("X and Y")
  '''
  print("\n🔄 Qrafik hazırlanır...")
  time.sleep(2)
  plt.show()